name: Frontend and Backend workflow

on:
  push:
  pull_request:
  workflow_dispatch:
    
jobs:
  install:
    uses: ./.github/workflows/prepare.yml

  check:
    uses: ./.github/workflows/prepare.yml
    needs: [install]
    with:
      action: 'check'

  compile:
    uses: ./.github/workflows/prepare.yml
    needs: [install]
    with:
      action: 'compile'

  lint:
    uses: ./.github/workflows/prepare.yml
    needs: [install]
    with:
      action: 'lint'
